services:
  - type: web
    name: kreatify-hub-ecommerce
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - fromDotEnv: true
