services:
  - type: web
    name: kreatify-hub-ecommerce
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - fromDotEnv: true
